baseURL = "rancherdesktop.io/"
languageCode = "en-us"
theme = "hugo-material"
title = "Rancher Desktop"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"]
googleAnalytics = 'UA-56382716-10'

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true

[menu]

  [[menu.main]]
    pre = "<i class='material-icons'>menu_book</i>"
    identifier = "docs"
    name = "Docs"
    url = "https://docs.rancherdesktop.io"
  [[menu.main]]
    pre = "<i class='fa fa-github'></i>"
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/rancher-sandbox/rancher-desktop/"

[params]
  custom_css = ["custom.css"]
  version = "0.7.1"
