baseURL = "https://rancher-sandbox.github.io/rancherdesktop.io/"
languageCode = "en-us"
theme = "projects-theme"
title = "Rancher Desktop"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"]
googleAnalytics = 'UA-56382716-10'

[menu]

  [[menu.main]]
    identifier = "docs"
    name = "Docs"
    url = "https://github.com/rancher-sandbox/rancher-desktop/tree/main/docs"

[params]
  github = "https://github.com/rancher-sandbox/rancher-desktop"
